import type { Metadata } from 'next'
import './globals.css'
import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'
import type { ReactNode } from 'react'
import { Footer } from '#components/footer'
import { Nav } from '#components/nav'
import { cn } from '#lib/utils'
import classes from './layout.module.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface Props {
  children: ReactNode
}

export default function Layout({ children }: Props) {
  return (
    <html lang="en">
      <body
        className={cn(GeistSans.variable, GeistMono.variable, 'antialiased')}
      >
        <main className={classes.main}>
          <Nav />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}
