name: deploy-hook

on:
  deployment_status:

jobs:
  main:
    #  && github.event.deployment.environment == 'production'
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2
      - run: |
          curl -X POST "${{ github.event.deployment_status.target_url }}/api/hooks/deploy" \
          -H "Authorization: Bearer ${{ secrets.BEARER_TOKEN }}"

